name: Build and Push Docker image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Batasi 1 build per cabang; kalau ada commit baru, batalkan yang lama
concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      # Buat log buildx lebih jelas (opsional)
      BUILDKIT_PROGRESS: plain

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Build multi-arch butuh QEMU; walau kita target amd64, ini aman & cepat
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/agent-challenge
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # targetkan linux/amd64 biar kompatibel dengan runner Nosana
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          # cache antar-run supaya build berikutnya lebih cepat
          cache-from: type=gha
          cache-to: type=gha,mode=max
